Minor fix

diff --git a/.github/workflows/upload-clean-ccache.yml b/.github/workflows/upload-clean-ccache.yml
--- a/.github/workflows/upload-clean-ccache.yml
+++ b/.github/workflows/upload-clean-ccache.yml
@@ -28,14 +28,14 @@ jobs:
 
       - name: Print result
         run: |
-          grep -B 100 -A 3 -e "Error 1" -e "[fail]" docker-compose.log || true
+          grep -B 100 -A 3 -e "Error 1" -e "\[fail\]" docker-compose.log || true
           ls data/crawl-master | xargs
         working-directory: server
 
       - name: Upload ccache
         run: |
           ./upload-ccache.sh "build-clean-ccache (from Action)"
-          ! grep -q -e "Error 1" -e "[fail]" docker-compose.log
+          ! grep -q -e "Error 1" -e "\[fail\]" docker-compose.log
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         working-directory: server
